name: Keep Render Alive

on:
  schedule:
    # Every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request to Render app
        run: |
          curl -s https://your-app.onrender.com/health || echo "App is asleep"
